# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # ============================================================================
  # Python Dependencies (pip/uv)
  # ============================================================================
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor/patch updates to reduce PR spam
    groups:
      # Development dependencies (linting, testing, formatting)
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "bandit*"
          - "mypy*"
          - "coverage*"
        update-types:
          - "minor"
          - "patch"

      # FastAPI ecosystem
      fastapi-ecosystem:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "starlette*"
          - "pydantic*"
        update-types:
          - "patch"

      # Database dependencies
      database:
        patterns:
          - "sqlalchemy*"
          - "alembic*"
          - "psycopg2*"
          - "asyncpg*"
        update-types:
          - "patch"

  # ============================================================================
  # Docker Base Images
  # ============================================================================
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"

  # ============================================================================
  # GitHub Actions
  # ============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
