# Pre-commit hooks for code quality
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # General fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements  # Check for debugger imports and breakpoints

  # Ruff - All-in-one Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: ['--fix']
      # Run the formatter
      - id: ruff-format

  # Type checking - MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--no-strict-optional']
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - sqlalchemy[mypy]
          - pydantic

  # Security checks - Bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ['-r', 'app/', '-ll', '--skip=B101,B601']


# Configuration for specific directories
files: ^(app|tests|scripts)/
exclude: |
  (?x)^(
    alembic/versions/.*\.py$|
    .*\.egg-info/.*$|
    build/.*$|
    dist/.*$|
    venv/.*$|
    \.git/.*$|
    __pycache__/.*$
  )